# Use official Python 3.10 image as base
FROM python:3.10-slim-bookworm

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsndfile1 \
    git \
    && rm -rf /var/lib/apt/lists/*

# Copy specific requirements file
COPY minuk/ai_service/requirements.txt /app/requirements.txt

# Install python dependencies
RUN pip install --no-cache-dir --upgrade pip && \
        pip install --no-cache-dir \
            --index-url https://download.pytorch.org/whl/cpu \
            --extra-index-url https://pypi.org/simple \
            -r requirements.txt

# Copy source code
COPY minuk /app/minuk

EXPOSE 8001

ENV PYTHONPATH=/app

# Run the Minuk application
CMD ["uvicorn", "minuk.ai_service.app:app", "--host", "0.0.0.0", "--port", "8001"]
