# Use official Python 3.10 image as base
FROM python:3.10-slim-bookworm

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsndfile1 \
    git \
    && rm -rf /var/lib/apt/lists/*

# Copy specific requirements file
COPY Voshan/ml-service/requirements.txt /app/requirements.txt

# Install python dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY Voshan /app/Voshan

EXPOSE 8002

ENV PYTHONPATH=/app

# Run the Voshan application
CMD ["uvicorn", "Voshan.ml-service.app:app", "--host", "0.0.0.0", "--port", "8002"]
